/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

                           
                           
/**
 *
 * @author x12384261
 */
public class Computer3 extends javax.swing.JFrame {
    Computer3array a;
    
    String name, password, workshop, subject;
    int student, date;
    double time;
    
    Computer3array[] ca;
    
    int count;
            
    /**
     * Creates new form Computer3
     */
    public Computer3() {
        initComponents();
        a = new Computer3array();
        
        ca = new Computer3array[150];
        count= 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NCI = new javax.swing.JLabel();
        HelpT = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        StudentNumber = new javax.swing.JLabel();
        StudentNumberBox = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        passwordbox = new javax.swing.JTextField();
        Workshop = new javax.swing.JLabel();
        workshopbox = new javax.swing.JTextField();
        DOW = new javax.swing.JLabel();
        DOWBox = new javax.swing.JTextField();
        TOW = new javax.swing.JLabel();
        TOWBox = new javax.swing.JTextField();
        Subject = new javax.swing.JLabel();
        subjectbox = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        NextBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(235, 342));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        HelpT.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        HelpT.setForeground(new java.awt.Color(0, 0, 102));
        HelpT.setText("<html>This page will help you book an apointment is the NCI collage.\n</html>");

        Name.setForeground(new java.awt.Color(204, 204, 0));
        Name.setText("Name:");

        StudentNumber.setForeground(new java.awt.Color(204, 204, 0));
        StudentNumber.setText("Student Number:");

        Password.setForeground(new java.awt.Color(204, 204, 0));
        Password.setText("Password:");

        Workshop.setForeground(new java.awt.Color(204, 204, 0));
        Workshop.setText("Workshop:");

        workshopbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workshopboxActionPerformed(evt);
            }
        });

        DOW.setForeground(new java.awt.Color(204, 204, 0));
        DOW.setText("Day of workshop:");

        DOWBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOWBoxActionPerformed(evt);
            }
        });

        TOW.setForeground(new java.awt.Color(204, 204, 0));
        TOW.setText("Time of workshop:");

        Subject.setForeground(new java.awt.Color(204, 204, 0));
        Subject.setText("Subject:");

        subjectbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectboxActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(0, 0, 102));
        Back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(204, 153, 0));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        NextBtn.setBackground(new java.awt.Color(0, 0, 102));
        NextBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NextBtn.setForeground(new java.awt.Color(204, 153, 0));
        NextBtn.setText("Submit");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 153, 0));
        jButton1.setText("show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 153, 0));
        jButton2.setText("save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("H:\\OOP\\OOP Project\\ncirl.gif")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NCI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HelpT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Name)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(namebox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(StudentNumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(StudentNumberBox))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Password)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(passwordbox))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Workshop)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(workshopbox))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(DOW)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DOWBox))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(TOW)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TOWBox))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Subject)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(subjectbox)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Back)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NextBtn)
                                        .addGap(14, 14, 14)
                                        .addComponent(jButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NCI, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HelpT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(namebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentNumber)
                    .addComponent(StudentNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(passwordbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Workshop)
                    .addComponent(workshopbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOW)
                    .addComponent(DOWBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TOW)
                    .addComponent(TOWBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subject)
                    .addComponent(subjectbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextBtn)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Back)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
          Computer2 myFrame = new Computer2();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        // TODO add your handling code here:
        name = namebox.getText();
        password = passwordbox.getText();
        workshop = workshopbox.getText();
        subject = subjectbox.getText();
        student = Integer.parseInt(StudentNumberBox.getText());
        date = Integer.parseInt(DOWBox.getText());
        time = Double.parseDouble(TOWBox.getText());
        
        a.setName(name);
        a.setWorkshop(workshop);
        a.setSubject(subject);
        a.setPassword(password);
        a.setStudent(student);
        a.setDate(date);
        a.setTime(time);
        
        ca[count] = a;
        count++;
    }//GEN-LAST:event_NextBtnActionPerformed

    private void workshopboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workshopboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workshopboxActionPerformed

    private void subjectboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectboxActionPerformed

    private void DOWBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOWBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOWBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(a.getDetails());
        JOptionPane.showMessageDialog(null,a.getDetails());
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        File outFile;
        FileOutputStream fileStream;
        ObjectOutputStream outStream;
        
        try{
            outFile = new File("output.data");
            fileStream = new FileOutputStream(outFile);
            outStream = new ObjectOutputStream(fileStream);
            
            outStream.writeObject(ca);
            
            JOptionPane.showMessageDialog(null,"save successfull");
            
            outStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Computer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Computer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Computer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Computer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Computer3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel DOW;
    private javax.swing.JTextField DOWBox;
    private javax.swing.JLabel HelpT;
    private javax.swing.JLabel NCI;
    private javax.swing.JLabel Name;
    private javax.swing.JButton NextBtn;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel StudentNumber;
    private javax.swing.JTextField StudentNumberBox;
    private javax.swing.JLabel Subject;
    private javax.swing.JLabel TOW;
    private javax.swing.JTextField TOWBox;
    private javax.swing.JLabel Workshop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField passwordbox;
    private javax.swing.JTextField subjectbox;
    private javax.swing.JTextField workshopbox;
    // End of variables declaration//GEN-END:variables
}
