/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author x12384261
 */
public class Computer2 extends javax.swing.JFrame {

    /**
     * Creates new form Computer2
     */
    public Computer2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NCI = new javax.swing.JLabel();
        CSP2 = new javax.swing.JLabel();
        NCIhelp = new javax.swing.JLabel();
        Drop = new javax.swing.JLabel();
        DropT = new javax.swing.JLabel();
        Moodle = new javax.swing.JLabel();
        MoodleT = new javax.swing.JLabel();
        Exam = new javax.swing.JLabel();
        ExamT = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        EmailBtn = new javax.swing.JButton();
        NextBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(314, 483));

        CSP2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CSP2.setForeground(new java.awt.Color(0, 0, 102));
        CSP2.setText("<html>Computer<br /> support<br /> page 2</html>");

        NCIhelp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NCIhelp.setForeground(new java.awt.Color(0, 0, 102));
        NCIhelp.setText("<html>6 ways how NCI can help you with<br /> computer support:</html>");

        Drop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Drop.setForeground(new java.awt.Color(204, 204, 0));
        Drop.setText("4: Drop in workshops ");

        DropT.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        DropT.setText("<html>Every week for first year studence the computer support service puts on a class to help them.These classes can be added on to your timetable after week 3 or 4 onwords. If you have a question you can just come it to the class to ask or if you have any other work to do (classwork or project work) you can come in an do it there will also be a lectuer present to help. There is no appointment needed you can just go in and do work that you need to get done.  </html>");

        Moodle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Moodle.setForeground(new java.awt.Color(204, 204, 0));
        Moodle.setText("5:Moodle");

        MoodleT.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        MoodleT.setText("<html>The Computing Support Service also has a Moodle page where you can find a schedule of \nextra classes and Drop in Workshop hours as well as past exam papers and revision \nmaterial for some modules.</html>\n");

        Exam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Exam.setForeground(new java.awt.Color(204, 204, 0));
        Exam.setText("6: Exam Revision");

        ExamT.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ExamT.setText("<html>Exam revision sessions will be held in the run up to<br /> each exam session. These sessions will  take you through<br /> past or sample exam questions<br /> and solutions in preparation for the exams.</html>");

        BackBtn.setBackground(new java.awt.Color(0, 0, 102));
        BackBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(204, 153, 0));
        BackBtn.setText("back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        EmailBtn.setBackground(new java.awt.Color(0, 0, 102));
        EmailBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EmailBtn.setForeground(new java.awt.Color(204, 153, 0));
        EmailBtn.setText("E-Mail");
        EmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailBtnActionPerformed(evt);
            }
        });

        NextBtn.setBackground(new java.awt.Color(0, 0, 102));
        NextBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NextBtn.setForeground(new java.awt.Color(204, 153, 0));
        NextBtn.setText("Next");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("H:\\OOP\\OOP Project\\ncirl.gif")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NCI)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BackBtn)
                                .addGap(31, 31, 31)
                                .addComponent(EmailBtn)
                                .addGap(29, 29, 29)
                                .addComponent(NextBtn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NCIhelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Drop)
                                .addComponent(Moodle)
                                .addComponent(MoodleT, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Exam)
                                .addComponent(ExamT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CSP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DropT, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NCI, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CSP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NCIhelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Drop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DropT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Moodle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MoodleT, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExamT, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn)
                    .addComponent(EmailBtn)
                    .addComponent(NextBtn))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailBtnActionPerformed
        /*
         * @reference
         * http://stackoverflow.com/questions/2357895/java-open-default-mail-application-and-create-new-mail-and-populate-to-and-subj
         */
        Desktop desktop;
if (Desktop.isDesktopSupported() 
    && (desktop = Desktop.getDesktop()).isSupported(Desktop.Action.MAIL)) {
  URI mailto = null;
            try {
                mailto = new URI("mailto:frances.sheridan@ncirl.ie?subject=Computing%20Support%20Query");
            } catch (URISyntaxException ex) {
                Logger.getLogger(Computer2.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                desktop.mail(mailto);
            } catch (IOException ex) {
                Logger.getLogger(Computer2.class.getName()).log(Level.SEVERE, null, ex);
            }
} else {
  // TODO fallback to some Runtime.exec(..) voodoo?
  throw new RuntimeException("desktop doesn't support mailto; mail is dead anyway ;)");
}
    }//GEN-LAST:event_EmailBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
         Computer myFrame = new Computer();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        // TODO add your handling code here:
          Computer3 myFrame = new Computer3();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_NextBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Computer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Computer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Computer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Computer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Computer2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel CSP2;
    private javax.swing.JLabel Drop;
    private javax.swing.JLabel DropT;
    private javax.swing.JButton EmailBtn;
    private javax.swing.JLabel Exam;
    private javax.swing.JLabel ExamT;
    private javax.swing.JLabel Moodle;
    private javax.swing.JLabel MoodleT;
    private javax.swing.JLabel NCI;
    private javax.swing.JLabel NCIhelp;
    private javax.swing.JButton NextBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
