package javaapplication1;

import javaapplication1.Disability;
import javaapplication1.HelpPage;
//import javaapplication1.LearningSupport;
import javaapplication1.Login;
import javaapplication1.MathsSupport;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x12384261
 */
public class Home extends javax.swing.JFrame {
private String name;


    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        textbox = new javax.swing.JLabel();
        pickASupport = new javax.swing.JLabel();
        computerbtn = new javax.swing.JButton();
        disabilitybtn = new javax.swing.JButton();
        mathbtn = new javax.swing.JButton();
        learningbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        mainbtn = new javax.swing.JButton();
        helpbtn = new javax.swing.JButton();
        nci = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();
        Welcome2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        textbox.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        textbox.setText("<html> <br />Welcome to the NCI Support page this page will help you<br /> with any problems you may have with your <br/>couse or with anyother problems you may have this page<br /> will have support in maths, computers and learning styles.it also had support for people with disabilities. </html>");

        pickASupport.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        pickASupport.setText("Pick a Support");

        computerbtn.setBackground(new java.awt.Color(0, 0, 102));
        computerbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        computerbtn.setForeground(new java.awt.Color(204, 153, 0));
        computerbtn.setText("Computer Support");
        computerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerbtnActionPerformed(evt);
            }
        });

        disabilitybtn.setBackground(new java.awt.Color(0, 0, 102));
        disabilitybtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        disabilitybtn.setForeground(new java.awt.Color(204, 153, 0));
        disabilitybtn.setText("Disability");
        disabilitybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilitybtnActionPerformed(evt);
            }
        });

        mathbtn.setBackground(new java.awt.Color(0, 0, 102));
        mathbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mathbtn.setForeground(new java.awt.Color(204, 153, 0));
        mathbtn.setText("Maths Support");
        mathbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathbtnActionPerformed(evt);
            }
        });

        learningbtn.setBackground(new java.awt.Color(0, 0, 102));
        learningbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        learningbtn.setForeground(new java.awt.Color(204, 153, 0));
        learningbtn.setText("Learning Support");
        learningbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningbtnActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(0, 0, 102));
        backbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backbtn.setForeground(new java.awt.Color(204, 153, 0));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        mainbtn.setBackground(new java.awt.Color(0, 0, 102));
        mainbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mainbtn.setForeground(new java.awt.Color(204, 153, 0));
        mainbtn.setText("Main");
        mainbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbtnActionPerformed(evt);
            }
        });

        helpbtn.setBackground(new java.awt.Color(0, 0, 102));
        helpbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        helpbtn.setForeground(new java.awt.Color(204, 153, 0));
        helpbtn.setText("Help");
        helpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpbtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("H:\\OOP\\OOP Project\\ncirl.gif")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(learningbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mathbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(disabilitybtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(computerbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(mainbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(helpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pickASupport, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(logo))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(nci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Welcome2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(logo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(nci, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Welcome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(pickASupport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(computerbtn)
                .addGap(18, 18, 18)
                .addComponent(disabilitybtn)
                .addGap(18, 18, 18)
                .addComponent(mathbtn)
                .addGap(18, 18, 18)
                .addComponent(learningbtn)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void setName(String name){
    this.name = name;
    Welcome.setText("Hello "+ name);
    

    

    

}
    private void computerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerbtnActionPerformed
        // TODO add your handling code here:
       Computer myFrame = new Computer();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_computerbtnActionPerformed

    private void disabilitybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilitybtnActionPerformed
        // TODO add your handling code here:
          Disability dialog = new Disability(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            
    }//GEN-LAST:event_disabilitybtnActionPerformed

    private void mathbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathbtnActionPerformed
        // TODO add your handling code here:
        MathsSupport myFrame = new MathsSupport();
        myFrame.setVisible(true);
    }//GEN-LAST:event_mathbtnActionPerformed

    private void learningbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningbtnActionPerformed
        // TODO add your handling code here:
      //  LearningSupport myFrame = new LearningSupport();
      //  myFrame.setVisible(true);
    }//GEN-LAST:event_learningbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        Login myFrame = new Login();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void mainbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbtnActionPerformed
        // TODO add your handling code here:
         Login myFrame = new Login();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_mainbtnActionPerformed

    private void helpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpbtnActionPerformed
        // TODO add your handling code here:
        HelpPage myFrame = new HelpPage();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_helpbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel Welcome2;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton computerbtn;
    private javax.swing.JButton disabilitybtn;
    private javax.swing.JButton helpbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton learningbtn;
    private javax.swing.JLabel logo;
    private javax.swing.JButton mainbtn;
    private javax.swing.JButton mathbtn;
    private javax.swing.JLabel nci;
    private javax.swing.JLabel pickASupport;
    private javax.swing.JLabel textbox;
    // End of variables declaration//GEN-END:variables
}
