/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * Author: Nicole Pasquetti x11527487
 */
package javaapplication1;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x11527487
 */
public class Login extends javax.swing.JFrame {
    
    private ArrayList <Coding> aList;
    private String name, type;
    private double weighting;
    private int count;
    

       
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        aList = new ArrayList <>();
        name = new String();
        type = new String ();
        weighting = 0.0;
        count = 0;
        //ArrayList Continued in the Home page
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nci = new javax.swing.JLabel();
        NciSupport = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        NTextField = new javax.swing.JTextField();
        Number = new javax.swing.JLabel();
        NoTextField = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Nci.setIcon(new javax.swing.ImageIcon("H:\\OOP\\OOP Project\\JavaApplication1\\logo-NCIRL.gif")); // NOI18N

        NciSupport.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NciSupport.setForeground(new java.awt.Color(0, 0, 102));
        NciSupport.setText("Welcome To NCI Support!");

        Name.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 204, 102));
        Name.setText("Name:");

        NTextField.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NTextField.setForeground(new java.awt.Color(0, 0, 102));
        NTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NTextFieldActionPerformed(evt);
            }
        });

        Number.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Number.setForeground(new java.awt.Color(255, 204, 102));
        Number.setText("Number:");

        NoTextField.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NoTextField.setForeground(new java.awt.Color(0, 0, 102));
        NoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoTextFieldActionPerformed(evt);
            }
        });

        SubmitButton.setBackground(new java.awt.Color(0, 0, 102));
        SubmitButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 204, 102));
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Nci, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(NciSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Nci, javax.swing.GroupLayout.PREFERRED_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NciSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(NTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
   
        
       
        
        //get text from textfields
        name = NTextField.getText();
        type = NTextField.getName();
        name = NoTextField.getText();
        type = NoTextField.getName();
       
       
        
        Coding a = new Coding();
        
        a.setName(name);
        a.setType(type);
     
       aList.add(a);
        
        //increment counter 
        count++;
        
    
        
        // TODO add your handling code here:
        File outFile;
        FileOutputStream fileStream;
        ObjectOutputStream outStream;
        
        try{
            outFile = new File("output.data");
            fileStream = new FileOutputStream(outFile);
            outStream = new ObjectOutputStream(fileStream);
            
            outStream.writeObject(a);
            
            JOptionPane.showMessageDialog(null,"Welcome" + NTextField.getText()+ NoTextField.getText());
          
            
            outStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        
        
        Home myFrame = new Home();
        myFrame.setVisible(true);
        myFrame.setName(name);
       
        dispose();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void NTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NTextFieldActionPerformed

    private void NoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NTextField;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Nci;
    private javax.swing.JLabel NciSupport;
    private javax.swing.JTextField NoTextField;
    private javax.swing.JLabel Number;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
