/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author x11527487
 */
public class MathsSupport extends javax.swing.JFrame {

    /**
     * Creates new form MathsSupport
     */
    public MathsSupport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MathsSupport = new javax.swing.JPanel();
        Nci = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();
        Maths = new javax.swing.JLabel();
        Support = new javax.swing.JLabel();
        Offer = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        ResourceButton = new javax.swing.JButton();
        Workshops = new javax.swing.JButton();
        Reading = new javax.swing.JButton();
        Sessions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(384, 493));

        MathsSupport.setBackground(new java.awt.Color(255, 255, 255));
        MathsSupport.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        MathsSupport.setPreferredSize(new java.awt.Dimension(384, 517));

        Nci.setIcon(new javax.swing.ImageIcon("H:\\OOP\\OOP Project\\JavaApplication1\\ncirl.gif")); // NOI18N

        Welcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Welcome.setForeground(new java.awt.Color(0, 0, 102));
        Welcome.setText("Welcome to");

        Maths.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Maths.setForeground(new java.awt.Color(0, 0, 102));
        Maths.setText("Maths");

        Support.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Support.setForeground(new java.awt.Color(0, 0, 102));
        Support.setText("Support!");

        Offer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Offer.setForeground(new java.awt.Color(204, 153, 0));
        Offer.setText("What We Have To Offer:");

        BackButton.setBackground(new java.awt.Color(0, 0, 102));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(204, 153, 0));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ResourceButton.setBackground(new java.awt.Color(0, 0, 102));
        ResourceButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResourceButton.setForeground(new java.awt.Color(204, 153, 0));
        ResourceButton.setText("Resource Videos");
        ResourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResourceButtonActionPerformed(evt);
            }
        });

        Workshops.setBackground(new java.awt.Color(0, 0, 102));
        Workshops.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Workshops.setForeground(new java.awt.Color(204, 153, 0));
        Workshops.setText("Workshops");
        Workshops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkshopsActionPerformed(evt);
            }
        });

        Reading.setBackground(new java.awt.Color(0, 0, 102));
        Reading.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Reading.setForeground(new java.awt.Color(204, 153, 0));
        Reading.setText("Reading Materials\n");
        Reading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadingActionPerformed(evt);
            }
        });

        Sessions.setBackground(new java.awt.Color(0, 0, 102));
        Sessions.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Sessions.setForeground(new java.awt.Color(204, 153, 0));
        Sessions.setText("Personal Sessions\n");
        Sessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SessionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MathsSupportLayout = new javax.swing.GroupLayout(MathsSupport);
        MathsSupport.setLayout(MathsSupportLayout);
        MathsSupportLayout.setHorizontalGroup(
            MathsSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MathsSupportLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MathsSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Offer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MathsSupportLayout.createSequentialGroup()
                        .addComponent(Nci, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(MathsSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MathsSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MathsSupportLayout.createSequentialGroup()
                                    .addComponent(Maths, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)))
                            .addComponent(Support, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(MathsSupportLayout.createSequentialGroup()
                        .addGroup(MathsSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MathsSupportLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(MathsSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Reading, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Workshops, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Sessions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(MathsSupportLayout.createSequentialGroup()
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(ResourceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        MathsSupportLayout.setVerticalGroup(
            MathsSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MathsSupportLayout.createSequentialGroup()
                .addGroup(MathsSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MathsSupportLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Maths, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Support, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Nci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Offer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Workshops, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reading, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sessions, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(MathsSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ResourceButton))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MathsSupport, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MathsSupport, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResourceButtonActionPerformed
 /*
         * @reference
         * http://www.codeproject.com/Questions/398241/how-to-open-url-in-java
         */
        try {
  Desktop desktop = java.awt.Desktop.getDesktop();
  URI oURL = new URI("https://myncistudent.ncirl.ie/StudentServicesAndSupport/StudentSupport/Mathematics/Resources/default.aspx");
  desktop.browse(oURL);
} catch (Exception e) {
  e.printStackTrace();
}      
   }//GEN-LAST:event_ResourceButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        Home myFrame = new Home();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadingActionPerformed
        // TODO add your handling code here:
        Reading myFrame = new Reading();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReadingActionPerformed

    private void WorkshopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkshopsActionPerformed
        // TODO add your handling code here:
        Workshops myFrame = new Workshops();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_WorkshopsActionPerformed

    private void SessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SessionsActionPerformed
        // TODO add your handling code here:
        Sessions myFrame = new Sessions();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_SessionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathsSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathsSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathsSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathsSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MathsSupport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Maths;
    private javax.swing.JPanel MathsSupport;
    private javax.swing.JLabel Nci;
    private javax.swing.JLabel Offer;
    private javax.swing.JButton Reading;
    private javax.swing.JButton ResourceButton;
    private javax.swing.JButton Sessions;
    private javax.swing.JLabel Support;
    private javax.swing.JLabel Welcome;
    private javax.swing.JButton Workshops;
    // End of variables declaration//GEN-END:variables
}
