/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author x11527487
 */
public class Workshops extends javax.swing.JFrame {

    /**
     * Creates new form Workshops
     */
    public Workshops() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Workshops = new javax.swing.JPanel();
        Nci = new javax.swing.JLabel();
        Wworkshops = new javax.swing.JLabel();
        and = new javax.swing.JLabel();
        ExamBased = new javax.swing.JLabel();
        Eworkshops = new javax.swing.JLabel();
        WorkshopLabel = new javax.swing.JLabel();
        EWorkshopLabel = new javax.swing.JLabel();
        Info = new javax.swing.JScrollPane();
        jLabel8 = new javax.swing.JLabel();
        Info2 = new javax.swing.JScrollPane();
        jLabel9 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Workshops.setBackground(new java.awt.Color(255, 255, 255));

        Nci.setIcon(new javax.swing.ImageIcon("H:\\OOP\\OOP Project\\JavaApplication1\\ncirl.gif")); // NOI18N

        Wworkshops.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Wworkshops.setForeground(new java.awt.Color(0, 0, 102));
        Wworkshops.setText("Workshops");

        and.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        and.setForeground(new java.awt.Color(0, 0, 102));
        and.setText("and");

        ExamBased.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ExamBased.setForeground(new java.awt.Color(0, 0, 102));
        ExamBased.setText("Exam Based");

        Eworkshops.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Eworkshops.setForeground(new java.awt.Color(0, 0, 102));
        Eworkshops.setText("Workshops");

        WorkshopLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        WorkshopLabel.setForeground(new java.awt.Color(204, 153, 0));
        WorkshopLabel.setText("Workshops ");

        EWorkshopLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EWorkshopLabel.setForeground(new java.awt.Color(204, 153, 0));
        EWorkshopLabel.setText("Exam Based Workshops");

        jLabel8.setText("<html>\nThis is where you will be able to<br />\nattend workshopsthat go through<br />\n everything you need to know in <br />\ndetail and it goes thorough it step<br />\n by step.<br />\n<br />\nTuesday       <br />                     \n12pm - 1pm\t\t<br />\nScr1\t<br />\t\n1pm - 2pm\t\t<br />\n1.01\t\t<br />\n4pm - 5pm\t<br />\n1.06\t<br />\n<br />\nThursday<br />\n10am- 11am<br />\n3.02<br />\n<br />\nFriday<br />\n3pm - 4pm<br />\nTheatre 2<br />\n10am - 11am<br />\n3.08<br />\n<br />\n");
        Info.setViewportView(jLabel8);

        jLabel9.setText("<html>\nThe Mathematics Support Service<br />\nwill be running dedicated Examination<br />\n Revision sessions for the August <br />\n2013 Repeat Examinations<br />\nThe sessions will concentrate on <br />\nthose typical past examination <br />\nquestions.<br />\n<br /> These sessions have been <br />\nreally effective and are quite popular<br />\n with all modules.<br />\nThe sessions will commence the<br />\n week beginning 11th <br />\nJuly and continue up till <br />\nexams end in August<br />\n<br />\nBAHACC1 BAHAHR1 BAHHRD1 BAHBMD1<br />\nQuantitative Analysis<br />\nMonday 9am - 11am Theatre 2<br />\nTuesday 9am - 11am Theatre 2<br />\n<br />\nHCBS1<br />\nQuantitative Analysis<br />\nMonday 2pm - 4pm Theatre 2<br />\nTuesday 2am - 4am Theatre 2<br />\n<br />\nHCBS1<br />\nQuantitative Analysis<br />\nMonday 2pm - 4pm Theatre 2<br />\nTuesday 2am - 4am Theatre 2<br />\n<br />\nHCBS2<br />\nQualitative and Quantitative Methods<br />\nWednesday 12am - 2pm Theatre 2 - QQ1<br />\nWednesday 3pm - 5pm Theatre 2 - QQ2<br />\n<br />\nBAHACC2 BAHHRD2<br />\nResearch Methods II<br />\nThursday 9am - 11am Theatre 2<br />\nFriday 9am - 11am Theatre 2<br />\n<br />\nBSHC1 BSHBIS1 HCC1<br />\nIntroduction to Mathematics for Computing<br />\nThursday 2pm - 4pm Theatre 2<br />\nThursday 5.30pm - 7.30pm Theatre 2<br />\nFriday 2pm - 4pm Theatre 2<br />");
        Info2.setViewportView(jLabel9);

        BackButton.setBackground(new java.awt.Color(0, 0, 102));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BackButton.setForeground(new java.awt.Color(204, 153, 0));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WorkshopsLayout = new javax.swing.GroupLayout(Workshops);
        Workshops.setLayout(WorkshopsLayout);
        WorkshopsLayout.setHorizontalGroup(
            WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkshopsLayout.createSequentialGroup()
                .addGroup(WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkshopsLayout.createSequentialGroup()
                            .addComponent(WorkshopLabel)
                            .addGap(47, 47, 47))
                        .addGroup(WorkshopsLayout.createSequentialGroup()
                            .addComponent(Nci, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(WorkshopsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Info)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WorkshopsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Eworkshops, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkshopsLayout.createSequentialGroup()
                                    .addGroup(WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ExamBased, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Wworkshops, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkshopsLayout.createSequentialGroup()
                                    .addComponent(and, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(64, 64, 64)))))
                    .addGroup(WorkshopsLayout.createSequentialGroup()
                        .addGroup(WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Info2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(EWorkshopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(WorkshopsLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        WorkshopsLayout.setVerticalGroup(
            WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkshopsLayout.createSequentialGroup()
                .addGroup(WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nci, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(WorkshopsLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Wworkshops, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(and, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExamBased, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eworkshops, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EWorkshopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkshopLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Info, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(Info2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Workshops, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Workshops, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        MathsSupport myFrame = new MathsSupport();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Workshops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Workshops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Workshops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Workshops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Workshops().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel EWorkshopLabel;
    private javax.swing.JLabel Eworkshops;
    private javax.swing.JLabel ExamBased;
    private javax.swing.JScrollPane Info;
    private javax.swing.JScrollPane Info2;
    private javax.swing.JLabel Nci;
    private javax.swing.JLabel WorkshopLabel;
    private javax.swing.JPanel Workshops;
    private javax.swing.JLabel Wworkshops;
    private javax.swing.JLabel and;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
